let etapas = [
    {
        titulo:'vereador',
        numeros:5,
        candidatos:[
            {
                numeros:31555,
                nome:'Aurélio Gomes',
                partido:'PT',
                fotos:[
                    {
                        url:'Aurélio_Gomes.jpg',
                        legenda:'Vereador',
                    }
                ],
                numeros:56565,
                nome:'Carlos Hermes',
                partido:'PC do B',
                fotos:[
                    {
                        url:'Carlos_Hermes.jpg',
                        legenda:'Vereador',
                    }
                ]
            },
        ]
    },
    {
        titulo:'prefeito',
        numeros:2,
        candidatos:[
            {
                numeros:99,
                nome:'Assis Ramos',
                partido:'PT',
                vice:'PrAlex',
                fotos:[
                    {
                        url:'Assis.jpg',
                        legenda:'Prefeito'
                    },
                    {
                        url:'PrAlex.jpg',
                        legenda:'Vice-Prefeito',
                        small:true
                    }
                ],
                numeros:99,
                nome:'Assis Ramos',
                partido:'PT',
                vice:'PrAlex',
                fotos:[
                    {
                        url:'Assis.jpg',
                        legenda:'Prefeito'
                    },
                    {
                        url:'PrAlex.jpg',
                        legenda:'Vice-Prefeito',
                        small:true
                    }
                ],
                numeros:45,
                nome:'Sebastião Madeira',
                partido:'PSDB',
                vice:'Brasmar',
                fotos:[
                    {
                        url:'Madeira.jpg',
                        legenda:'Prefeito'
                    },
                    {
                        url:'Rodrigo.jpg',
                        legenda:'Vice-Prefeito',
                        small:true
                    }
                ]
            }
        ]
    }
]